# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React Build Deploy

on:
  push:
    branches: [ "master" ]

permissions:
    pages: write      # to deploy to Pages
    id-token: write 
    contents: write

jobs:
  build:

    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ''
    - name: Use Node.js EIGHTEERN
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
  
    - run: npm i
      shell: bash
    - run: npm run build --if-present

    - run: echo prockpoints.store > build/CNAME

    - name: SEND IT TO PAGES HQ PLEASE
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build