# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React Build Deploy

on:
  push:
    branches: [ "master" ]

permissions: 
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js EIGHTEERN
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
  
    - run: npm i
      shell: bash
    - run: npm run build --if-present
    - name: 'Checkout docs branch'
      uses: actions/checkout@v3
      with:
        ref: gh-pages
  
    - name: 'Moving and Groving'
      run: |
        git fetch master --depth 1
        git checkout master --no-overlay -- build
        rm -r static
        cp -rp build/* . 
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        commit_message: DEPLoyytt the PRpcokip POINTS!!
        add_options: '-f'
        file_pattern: build
        skip_dirty_check: true
